### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by JuliaTyumen** [dimitrov-adrian/ckfinder-watermark-plugin#1]
Dear Adrian,

I try to use your plugin but unfortunately I failed with it. My config file ckfinder/config.js is:

```
var config = {};

config.plugins = [
  'Watermark'
];

config.Watermark = {
  watermarks: [
    {
      file: 'http://patterneasy.com/sites/default/files/watermark-new.png',
      label: 'Example Watermark',
      size: '10',
      position: 'top left'
    }
  ]
};

CKFinder.define( config );
```

Also I enabled plugin in ckfinder/config.php:

`$config['plugins'][] = 'Watermark';`

When I try to upload images I get an "Unknown error" message (see screenshot). Original file is uploading normally, but without any watermark.

What am I doing wrong? My version of CKFinder is 3.3.0, with CKEditor ver 4.5.10.
![scrsht143](https://cloud.githubusercontent.com/assets/11813612/17054765/5aab82ea-5022-11e6-8d58-f28901e7187f.PNG)

**Comment by JuliaTyumen** [comment]
Update. I figured out that it's because of CSRF protection in Laravel. I got "exception 'Illuminate\Session\TokenMismatchException'" in my errorlog.

I didn't figure out how it can be solved yet. There should be token parameter in some request.

**Comment by dimitrov-adrian** [comment]
Actually CKFinder have nothing to do with Laravel. Also the plugin do nothing on image upload. It add extra button and dialog where images could be processed.
Could you provide additional information about steps you take.

**Comment by JuliaTyumen** [comment]
Hi Adrian,

Thanks for your reply!

> Actually CKFinder have nothing to do with Laravel

Yes by default, but I added Laravel Authentification function to disallow anonymous using of CKFinder.

I removed this function, and I see that it works without it. And yes, the problem wasn't in this plugin. I'll try to authentificate users in CKFinder by some other way.

Thanks for your help!
